# **How Perceptrons Learn - Intuition, Code, and Edge Cases**

In [121]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

---
---

## **Perceptrons from scratch**

### **Main Implementation**

In [122]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f"Weights: \n{self.weights}\n")

        self.eta = eta
        self.epochs = epochs

    def activation_func(self, inputs, weights):
        z = np.dot(inputs, weights)
        return np.where(z<1, 0, 1)

    def fit(self, X, y):
        self.X = X
        self.y = y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}\n")

        for epoch in range(self.epochs):
            print((f"Epoch: {epoch}"))

            y_hat = self.activation_func(X_with_bias, self.weights)
            print((f"Predictions: \n{y_hat}"))

            error = self.y - y_hat
            print(f"Error: \n{error}")

            self.weights = self.weights + (self.eta * np.dot(X_with_bias.T, error))
            print(f"Updated weights: \n{self.weights}")

            print("#############\n")


    def predict(self, X):
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]

        return self.activation_func(X_with_bias, self.weights)

---

### **AND Gate**

In [123]:
AND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}

AND = pd.DataFrame(AND)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [124]:
X = AND.drop("y", axis=1)
y = AND["y"]
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [125]:
and_model = Perceptron(eta=0.5, epochs=10)
and_model.fit(X,y)

Weights:
[1.30842408e-04 2.57088675e-06 7.91885158e-05]

X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]

Epoch: 0
Predictions:
[0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights:
[ 0.50013084  0.50000257 -0.49992081]
#############

Epoch: 1
Predictions:
[0 0 1 1]
Error:
0    0
1    0
2   -1
3    0
Name: y, dtype: int64
Updated weights:
[1.30842408e-04 5.00002571e-01 7.91885158e-05]
#############

Epoch: 2
Predictions:
[0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights:
[ 0.50013084  1.00000257 -0.49992081]
#############

Epoch: 3
Predictions:
[0 1 1 1]
Error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights:
[1.30842408e-04 5.00002571e-01 5.00079189e-01]
#############

Epoch: 4
Predictions:
[0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights:
[5.00130842e-01 1.00000257e+00 7.91885158e-05]
#############

Epoch: 5
Predictions:
[0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[5.00130842e-01 1.00000257e+00 7.91885158e-05]
#############

Epoch: 6
Predictions:
[0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[5.00130842e-01 1.00000257e+00 7.91885158e-05]
#############

Epoch: 7
Predictions:
[0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[5.00130842e-01 1.00000257e+00 7.91885158e-05]
#############

Epoch: 8
Predictions:
[0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[5.00130842e-01 1.00000257e+00 7.91885158e-05]
#############

Epoch: 9
Predictions:
[0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[5.00130842e-01 1.00000257e+00 7.91885158e-05]
#############

---

### **OR Gate**

In [126]:
OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,1]
}

OR = pd.DataFrame(OR)

X = OR.drop("y", axis=1)
y = OR["y"]
y.to_frame()

or_model = Perceptron(eta=0.5, epochs=10)
or_model.fit(X,y)

Weights:
[6.18160874e-05 5.45235092e-06 1.03754014e-04]

X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]

Epoch: 0
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -1.49989625]
#############

Epoch: 1
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 2
Predictions:
[0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 3
Predictions:
[0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 4
Predictions:
[0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 5
Predictions:
[0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 6
Predictions:
[0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 7
Predictions:
[0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 8
Predictions:
[0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 9
Predictions:
[0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights:
[ 1.00006182  1.00000545 -0.99989625]
#############

---

### **XOR Gate**

In [127]:
XOR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,0]
}

XOR = pd.DataFrame(XOR)

X = XOR.drop("y", axis=1)
y = XOR["y"]
y.to_frame()

xor_model = Perceptron(eta=0.1, epochs=1000)
xor_model.fit(X,y)

Streaming output truncated to the last 5000 lines.
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 616
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 617
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 618
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 619
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 620
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 621
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 622
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 623
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 624
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 625
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 626
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 627
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 628
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 629
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 630
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 631
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 632
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 633
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 634
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 635
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 636
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 637
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 638
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 639
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 640
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 641
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 642
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 643
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 644
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 645
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 646
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 647
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 648
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 649
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 650
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 651
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 652
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 653
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 654
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 655
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 656
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 657
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 658
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 659
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 660
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 661
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 662
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 663
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 664
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 665
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 666
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 667
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 668
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 669
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 670
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 671
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 672
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 673
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 674
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 675
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 676
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 677
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 678
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 679
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 680
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 681
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 682
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 683
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 684
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 685
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 686
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 687
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 688
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 689
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 690
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 691
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 692
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 693
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 694
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 695
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 696
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 697
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 698
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 699
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 700
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 701
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 702
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 703
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 704
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 705
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 706
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 707
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 708
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 709
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 710
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 711
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 712
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 713
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 714
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 715
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 716
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 717
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 718
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 719
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 720
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 721
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 722
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 723
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 724
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 725
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 726
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 727
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 728
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 729
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 730
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 731
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 732
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 733
Predictions:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights:
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 734
Predictions:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights:

---
---